<?php

return [
    'variants' => [

        'default' => [
            'background'          => 'bg-white dark:bg-slate-900',
            'pageBackground'      => 'bg-slate-100 dark:bg-slate-800',
            'text'                => 'text-slate-800 dark:text-slate-200',
            'border'              => 'border-slate-200 dark:border-slate-700',
            'shadow'              => 'shadow-slate-300/50 dark:shadow-slate-900/50',
            'ring'                => 'ring-slate-200 dark:ring-slate-700 ring-offset-slate-100 dark:ring-offset-slate-800',
            'hover'               => 'hover:bg-slate-300 hover:dark:bg-slate-900 hover:from-slate-400 hover:to-slate-700 hover:text-slate-800/70 hover:dark:text-slate-400/70',
            'focus'               => 'focus-within:outline focus-within:outline-slate-600 dark:focus-within:outline-slate-400 focus-within:outline-2',
            'active'              => 'bg-slate-300 dark:bg-slate-900 from-slate-400 to-slate-700',
            'gradient'            => 'bg-gradient-to-br from-slate-200 to-slate-100 text-slate-800',
            'divide'              => 'divide-slate-300 dark:divide-slate-700',
            'accent'              => 'accent-slate-600 hover:accent-slate-700',
            'errorBorder'         => 'border-red-800 dark:border-red-400',
            'errorText'           => 'text-red-800 dark:text-red-400',
            'highlightBorder'     => 'border-slate-700',
            'highlightDarkBorder' => 'dark:border-slate-100',
            'inactiveBorder'      => 'border-slate-100',
            'inactiveDarkBorder'  => 'dark:border-slate-700',
        ],

        'dark' => [
            'background'          => 'bg-slate-900',
            'pageBackground'      => 'bg-zinc-100 dark:bg-zinc-800',
            'text'                => 'text-slate-300',
            'border'              => 'border-slate-700',
            'shadow'              => 'shadow-slate-900/10',
            'ring'                => 'ring-slate-700 ring-offset-slate-800',
            'hover'               => 'hover:bg-slate-800 hover:from-slate-400 hover:to-slate-700',
            'focus'               => 'focus-within:outline focus-within:outline-slate-900 focus-within:outline-2',
            'active'              => 'bg-slate-800 from-slate-400 to-slate-700',
            'gradient'            => 'bg-gradient-to-br from-slate-700 to-slate-400 text-slate-100',
            'divide'              => 'divide-slate-800',
            'accent'              => 'accent-slate-600 hover:accent-slate-700',
            'errorBorder'         => 'border-red-400',
            'errorText'           => 'text-red-400',
            'highlightBorder'     => 'border-slate-700',
            'highlightDarkBorder' => '',
            'inactiveBorder'      => 'border-slate-100',
            'inactiveDarkBorder'  => '',
        ],

        'light' => [
            'background'          => 'bg-slate-50/80',
            'pageBackground'      => 'bg-zinc-100 dark:bg-zinc-800',
            'text'                => 'text-slate-800',
            'border'              => 'border-slate-200',
            'shadow'              => 'shadow-slate-500/10',
            'ring'                => 'ring-slate-200 ring-offset-slate-100',
            'hover'               => 'hover:bg-slate-300 hover:from-slate-400 hover:to-slate-700 hover:text-slate-800/70',
            'focus'               => 'focus-within:outline focus-within:outline-slate-600 focus-within:outline-2',
            'active'              => 'bg-slate-300 from-slate-400 to-slate-700',
            'gradient'            => 'bg-gradient-to-br from-slate-700 to-slate-400 text-slate-100',
            'divide'              => 'divide-slate-200',
            'accent'              => 'accent-slate-600 hover:accent-slate-700',
            'errorBorder'         => 'border-red-800',
            'errorText'           => 'text-red-800',
            'highlightBorder'     => 'border-slate-700',
            'highlightDarkBorder' => '',
            'inactiveBorder'      => 'border-slate-100',
            'inactiveDarkBorder'  => '',
        ],

        'brand' => [
            'background'          => 'bg-brand-200 dark:bg-brand-800',
            'pageBackground'      => 'bg-zinc-100 dark:bg-zinc-800',
            'text'                => 'text-brand-800 dark:text-brand-200',
            'border'              => 'border-brand-300 dark:border-brand-900',
            'shadow'              => 'shadow-brand-300/50 dark:shadow-brand-900/50',
            'ring'                => 'ring-brand-200 dark:ring-brand-700 ring-offset-brand-100 dark:ring-offset-brand-800',
            'hover'               => 'hover:bg-brand-300 hover:dark:bg-brand-900 hover:from-brand-400 hover:to-brand-700 hover:text-brand-800/70 hover:dark:text-brand-400/70',
            'focus'               => 'focus-within:outline focus-within:outline-brand-600 dark:focus-within:outline-brand-400 focus-within:outline-2',
            'active'              => 'bg-brand-300 dark:bg-brand-900 from-brand-400 to-brand-700',
            'gradient'            => 'bg-gradient-to-br from-brand-700 to-brand-400 text-brand-100',
            'divide'              => 'divide-brand-300 dark:divide-brand-900',
            'accent'              => 'accent-brand-600 hover:accent-brand-700',
            'errorBorder'         => 'border-brand-400 dark:border-brand-950',
            'errorText'           => 'text-brand-950 dark:text-brand-400',
            'highlightBorder'     => 'border-brand-700',
            'highlightDarkBorder' => 'dark:border-brand-100',
            'inactiveBorder'      => 'border-brand-100',
            'inactiveDarkBorder'  => 'dark:border-brand-700',
        ],

        'primary' => [
            'background'          => 'bg-blue-200 dark:bg-blue-700',
            'pageBackground'      => 'bg-zinc-100 dark:bg-zinc-800',
            'text'                => 'text-blue-800 dark:text-blue-200',
            'border'              => 'border-blue-300 dark:border-blue-900',
            'shadow'              => 'shadow-blue-300/50 dark:shadow-blue-900/50',
            'ring'                => 'ring-blue-200 dark:ring-blue-700 ring-offset-blue-100 dark:ring-offset-blue-800',
            'hover'               => 'hover:bg-blue-300 hover:dark:bg-blue-800 hover:from-blue-400 hover:to-blue-700 hover:text-blue-800/70 hover:dark:text-blue-400/70',
            'focus'               => 'focus-within:outline focus-within:outline-blue-600 dark:focus-within:outline-blue-400 focus-within:outline-2',
            'active'              => 'bg-blue-300 dark:bg-blue-900 from-blue-400 to-blue-700',
            'gradient'            => 'bg-gradient-to-br from-blue-700 to-blue-400 text-blue-100',
            'divide'              => 'divide-blue-300 dark:divide-blue-900',
            'accent'              => 'accent-blue-600 hover:accent-blue-700',
            'errorBorder'         => 'border-blue-500 dark:border-blue-950',
            'errorText'           => 'text-blue-950 dark:text-blue-400',
            'highlightBorder'     => 'border-blue-700',
            'highlightDarkBorder' => 'dark:border-blue-100',
            'inactiveBorder'      => 'border-blue-100',
            'inactiveDarkBorder'  => 'dark:border-blue-700',
        ],

        'secondary' => [
            'background'          => 'bg-slate-200 dark:bg-slate-700',
            'pageBackground'      => 'bg-zinc-100 dark:bg-zinc-800',
            'text'                => 'text-slate-800 dark:text-slate-200',
            'border'              => 'border-slate-300 dark:border-slate-900',
            'shadow'              => 'shadow-slate-300/50 dark:shadow-slate-900/50',
            'ring'                => 'ring-slate-200 dark:ring-slate-700 ring-offset-slate-100 dark:ring-offset-slate-800',
            'hover'               => 'hover:bg-slate-300 hover:dark:bg-slate-900 hover:from-slate-400 hover:to-slate-700 hover:text-slate-800/70 hover:dark:text-slate-400/70',
            'focus'               => 'focus-within:outline focus-within:outline-slate-600 dark:focus-within:outline-slate-400 focus-within:outline-2',
            'active'              => 'bg-slate-300 dark:bg-slate-900 from-slate-400 to-slate-700',
            'gradient'            => 'bg-gradient-to-br from-slate-700 to-slate-400 text-slate-100',
            'divide'              => 'divide-slate-300 dark:divide-slate-900',
            'accent'              => 'accent-slate-600 hover:accent-slate-700',
            'errorBorder'         => 'border-slate-500 dark:border-slate-950',
            'errorText'           => 'text-slate-950 dark:text-slate-400',
            'highlightBorder'     => 'border-slate-700',
            'highlightDarkBorder' => 'dark:border-slate-100',
            'inactiveBorder'      => 'border-slate-100',
            'inactiveDarkBorder'  => 'dark:border-slate-700',
        ],

        'success' => [
            'background'          => 'bg-emerald-200 dark:bg-emerald-700',
            'pageBackground'      => 'bg-zinc-100 dark:bg-zinc-800',
            'text'                => 'text-emerald-800 dark:text-emerald-200',
            'border'              => 'border-emerald-300 dark:border-emerald-900',
            'shadow'              => 'shadow-emerald-300/50 dark:shadow-emerald-900/50',
            'ring'                => 'ring-emerald-200 dark:ring-emerald-700 ring-offset-emerald-100 dark:ring-offset-emerald-800',
            'hover'               => 'hover:bg-emerald-300 hover:dark:bg-emerald-900 hover:from-emerald-400 hover:to-emerald-700 hover:text-emerald-800/70 hover:dark:text-emerald-400/70',
            'focus'               => 'focus-within:outline focus-within:outline-emerald-600 dark:focus-within:outline-emerald-400 focus-within:outline-2',
            'active'              => 'bg-emerald-300 dark:bg-emerald-900 from-emerald-400 to-emerald-700',
            'gradient'            => 'bg-gradient-to-br from-emerald-700 to-emerald-400 text-emerald-100',
            'divide'              => 'divide-emerald-300 dark:divide-emerald-900',
            'accent'              => 'accent-emerald-600 hover:accent-emerald-700',
            'errorBorder'         => 'border-emerald-500 dark:border-emerald-950',
            'errorText'           => 'text-emerald-950 dark:text-emerald-400',
            'highlightBorder'     => 'border-emerald-700',
            'highlightDarkBorder' => 'dark:border-emerald-100',
            'inactiveBorder'      => 'border-emerald-100',
            'inactiveDarkBorder'  => 'dark:border-emerald-700',
        ],

        'warning' => [
            'background'          => 'bg-orange-200 dark:bg-orange-700',
            'pageBackground'      => 'bg-zinc-100 dark:bg-zinc-800',
            'text'                => 'text-orange-800 dark:text-orange-200',
            'border'              => 'border-orange-300 dark:border-orange-900',
            'shadow'              => 'shadow-orange-300/50 dark:shadow-orange-900/50',
            'ring'                => 'ring-orange-200 dark:ring-orange-700 ring-offset-orange-100 dark:ring-offset-orange-800',
            'hover'               => 'hover:bg-orange-300 hover:dark:bg-orange-900 hover:from-orange-400 hover:to-orange-700 hover:text-orange-800/70 hover:dark:text-orange-400/70',
            'focus'               => 'focus-within:outline focus-within:outline-orange-600 dark:focus-within:outline-orange-400 focus-within:outline-2',
            'active'              => 'bg-orange-300 dark:bg-orange-900 from-orange-400 to-orange-700',
            'gradient'            => 'bg-gradient-to-br from-orange-700 to-orange-400 text-orange-100',
            'divide'              => 'divide-orange-300 dark:divide-orange-900',
            'accent'              => 'accent-orange-600 hover:accent-orange-700',
            'errorBorder'         => 'border-orange-500 dark:border-orange-950',
            'errorText'           => 'text-orange-950 dark:text-orange-400',
            'highlightBorder'     => 'border-orange-700',
            'highlightDarkBorder' => 'dark:border-orange-100',
            'inactiveBorder'      => 'border-orange-100',
            'inactiveDarkBorder'  => 'dark:border-orange-700',
        ],

        'danger' => [
            'background'          => 'bg-red-200 dark:bg-red-700',
            'pageBackground'      => 'bg-zinc-100 dark:bg-zinc-800',
            'text'                => 'text-red-800 dark:text-red-200',
            'border'              => 'border-red-300 dark:border-red-900',
            'shadow'              => 'shadow-red-300/50 dark:shadow-red-900/50',
            'ring'                => 'ring-red-200 dark:ring-red-700 ring-offset-red-100 dark:ring-offset-red-800',
            'hover'               => 'hover:bg-red-300 hover:dark:bg-red-900 hover:from-red-400 hover:to-red-700 hover:text-red-800/70 hover:dark:text-red-400/70',
            'focus'               => 'focus-within:outline focus-within:outline-red-600 dark:focus-within:outline-red-400 focus-within:outline-2',
            'active'              => 'bg-red-300 dark:bg-red-900 from-red-400 to-red-700',
            'gradient'            => 'bg-gradient-to-br from-red-700 to-red-400 text-red-100',
            'divide'              => 'divide-red-300 dark:divide-red-900',
            'accent'              => 'accent-red-600 hover:accent-red-700',
            'errorBorder'         => 'border-red-500 dark:border-red-950',
            'errorText'           => 'text-red-950 dark:text-red-400',
            'highlightBorder'     => 'border-red-700',
            'highlightDarkBorder' => 'dark:border-red-100',
            'inactiveBorder'      => 'border-red-100',
            'inactiveDarkBorder'  => 'dark:border-red-700',
        ],
    ],
];
