<?php

// config for Andach/LaravelViewComponents
return [
    'enable_component_test' => false,

    'pagination' => [
        'simple'   => 'view-components::pagination.simple',
        'standard' => 'view-components::pagination.standard',
    ],

    'views' => [
        'alert'                             => 'view-components::general.alert',
        'attachments-and-comments'          => 'view-components::general.attachments-and-comments',
        'avatar'                            => 'view-components::general.avatar',
        'breadcrumbs'                       => 'view-components::layouts.breadcrumbs',
        'button'                            => 'view-components::general.button',
        'card'                              => 'view-components::general.card',
        'chat'                              => 'view-components::general.chat',
        'checkbox'                          => 'view-components::forms.checkbox',
        'code'                              => 'view-components::general.code',
        'content'                           => 'view-components::layouts.content',
        'dark-toggle'                       => 'view-components::layouts.dark-toggle',
        'error'                             => 'view-components::layouts.error',
        'faq'                               => 'view-components::general.faq',
        'footer'                            => 'view-components::layouts.footer',
        'form'                              => 'view-components::forms.form',
        'form-error'                        => 'view-components::forms.form-error',
        'form-checkbox-icon'                => 'view-components::general.form-checkbox-icon',
        'form-section'                      => 'view-components::general.form-section',
        'h'                                 => 'view-components::general.h',
        'header'                            => 'view-components::layouts.header',
        'header-left'                       => 'view-components::layouts.header-left',
        'header-mobile'                     => 'view-components::layouts.header-mobile',
        'header-right'                      => 'view-components::layouts.header-right',
        'input'                             => 'view-components::forms.input',
        'label'                             => 'view-components::forms.label',
        'layout'                            => 'view-components::layouts.layout',
        'main'                              => 'view-components::layouts.main',
        'menu'                              => 'view-components::layouts.menu',
        'menu-group'                        => 'view-components::general.menu-group',
        'no-results'                        => 'view-components::general.no-results',
        'progress-bar'                      => 'view-components::general.progress-bar',
        'radio'                             => 'view-components::forms.radio',
        'search'                            => 'view-components::layouts.search',
        'select'                            => 'view-components::forms.select',
        'service-button'                    => 'view-components::general.service-button',
        'sessions'                          => 'view-components::layouts.sessions',
        'sidebar'                           => 'view-components::layouts.sidebar',
        'sidebar-footer'                    => 'view-components::layouts.sidebar-footer',
        'sidebar-menu'                      => 'view-components::layouts.sidebar-menu',
        'sidebar-top'                       => 'view-components::layouts.sidebar-top',
        'submit'                            => 'view-components::forms.submit',
        'table'                             => 'view-components::general.table',
        'textarea'                          => 'view-components::forms.textarea',
    ],
];
